source "https://rubygems.org"
gem 'sinatra'
gem 'sinatra-contrib'
gem 'twilio-ruby', '5.33.1'
gem 'dotenv'
gem 'httparty', '0.18.0'
gem 'json', '2.3.0'
gem 'giphy', '3.0.0'
gem 'faraday', '0.9'
gem 'open-weather', '0.11'
